# Generated by Django 3.0 on 2023-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='productimage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
