# Generated by Django 4.2 on 2023-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lifesure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policytable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
